version: "3.8"

services:
  rust-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /dev:/dev
      - claude-code-bashhistory-embedded-engr:/commandhistory
      - claude-code-config-embedded-engr:/home/vscode/.claude
    command: sleep infinity
    environment:
      - SHELL=/bin/zsh
      - CLAUDE_CONFIG_DIR=/home/vscode/.claude
    user: vscode
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb

volumes:
  claude-code-bashhistory-embedded-engr:
  claude-code-config-embedded-engr:
